### ISSUE TITLE
Hit end of file before finding size

### ISSUE THREAD

**Issue by sudo-nice** [Roughsketch/imagesize#10]
The error happens for this [image].

[image]: https://mega.nz/#!PwA2FQSY!ewSEwavNFaaCKDqTAFu0XJvpd8RB3_iefS8su3AahyM

**Comment by Roughsketch** [comment]
I can't figure out where the dimensions are for this image, so it looks like it's in some format that's not supported. Even searching in a hex editor I can't find them.

**Comment by sudo-nice** [comment]
`identify` (which is shipped with imagemagick) reports:
```
bf9c2c39b6.jpg JPEG 4980x3321 4980x3321+0+0 8-bit sRGB 1.88553MiB 0.000u 0:00.000
```

**Comment by Roughsketch** [comment]
Found the issue with exiftool. Looks like the SOF tag was FFC1 but I only look for C0 or C2. Will push a fix here soon.

**Comment by Roughsketch** [comment]
v0.8.5 released, all tests including that image are working with the change.

Thank you very much for the issue!

**Comment by sudo-nice** [comment]
That's really great, thanks a lot!

**Comment by sudo-nice** [comment]
I managed to hit the issue again, this time for this [image].

[image]: https://0x0.st/i30Y.jpg

**Comment by sudo-nice** [comment]
Thank you again.
