### ISSUE TITLE
support for PBM/PGM/PPM

### ISSUE THREAD

**Issue by akonneker** [Roughsketch/imagesize#14]
I recently found myself with a dataset containing PPM files, which seems like an especially simple addition to this library based on the format overview on [wikipedia](https://en.wikipedia.org/wiki/Netpbm).

**Comment by Roughsketch** [comment]
It actually seems a bit more complex than other formats since I'd need to handle comments and newline/no newline versions. However it doesn't seem that bad. I don't know when I'll have free time to do it, but will add it to the list of formats at some point most likely.

Thanks for the suggestion.
