### ISSUE TITLE
How much data required to determine image format and dimensions?

### ISSUE THREAD

**Issue by katyo** [Roughsketch/imagesize#5]
I tried to use this awesome lib with image data from streams.
Because the image data incomplete I need a way to get "not enough data" error or know how much bytes of header required to  determine.
I think this case quite differs from `CorruptedImage` or `NotSupported`.

**Comment by katyo** [comment]
As I understand when not enough data provided I get `IO Error` of kind `UnexpectedEof`. But it isn't so for too short headers because `image_type()` returns `ImageType::Unknown` (not error).

**Comment by Roughsketch** [comment]
Closed since #6 was merged. Thanks.
